//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassiveShell {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PassiveShell.IPassiveShell")]
    public interface IPassiveShell {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveShellPassiveshell/IsTransferingData", ReplyAction="http://tempuri.org/IActiveShellPassiveshell/IsTransferingDataResponse")]
        bool IsTransferingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveShellPassiveshell/IsTransferingData", ReplyAction="http://tempuri.org/IActiveShellPassiveshell/IsTransferingDataResponse")]
        System.Threading.Tasks.Task<bool> IsTransferingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveShellPassiveshell/StartTransferData", ReplyAction="http://tempuri.org/IActiveShellPassiveshell/StartTransferDataResponse")]
        void StartTransferData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveShellPassiveshell/StartTransferData", ReplyAction="http://tempuri.org/IActiveShellPassiveshell/StartTransferDataResponse")]
        System.Threading.Tasks.Task StartTransferDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveClientRun", ReplyAction="http://tempuri.org/IPassiveShell/PassiveClientRunResponse")]
        bool PassiveClientRun(string id, string taskId, string baseLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveClientRun", ReplyAction="http://tempuri.org/IPassiveShell/PassiveClientRunResponse")]
        System.Threading.Tasks.Task<bool> PassiveClientRunAsync(string id, string taskId, string baseLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveNextCommand", ReplyAction="http://tempuri.org/IPassiveShell/PassiveNextCommandResponse")]
        System.Tuple<string, string, string> PassiveNextCommand(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveNextCommand", ReplyAction="http://tempuri.org/IPassiveShell/PassiveNextCommandResponse")]
        System.Threading.Tasks.Task<System.Tuple<string, string, string>> PassiveNextCommandAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/CommandResponse", ReplyAction="http://tempuri.org/IPassiveShell/CommandResponseResponse")]
        void CommandResponse(string id, string taskId, string baseLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/CommandResponse", ReplyAction="http://tempuri.org/IPassiveShell/CommandResponseResponse")]
        System.Threading.Tasks.Task CommandResponseAsync(string id, string taskId, string baseLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/HasCommand", ReplyAction="http://tempuri.org/IPassiveShell/HasCommandResponse")]
        bool HasCommand(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/HasCommand", ReplyAction="http://tempuri.org/IPassiveShell/HasCommandResponse")]
        System.Threading.Tasks.Task<bool> HasCommandAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/HasUploadCommand", ReplyAction="http://tempuri.org/IPassiveShell/HasUploadCommandResponse")]
        bool HasUploadCommand(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/HasUploadCommand", ReplyAction="http://tempuri.org/IPassiveShell/HasUploadCommandResponse")]
        System.Threading.Tasks.Task<bool> HasUploadCommandAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/HasDownloadCommand", ReplyAction="http://tempuri.org/IPassiveShell/HasDownloadCommandResponse")]
        bool HasDownloadCommand(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/HasDownloadCommand", ReplyAction="http://tempuri.org/IPassiveShell/HasDownloadCommandResponse")]
        System.Threading.Tasks.Task<bool> HasDownloadCommandAsync(string id);
        
        // CODEGEN: Generating message contract since the operation PassiveDownloadedFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveDownloadedFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveDownloadedFileResponse")]
        PassiveShell.PassiveDownloadedFileResponse PassiveDownloadedFile(PassiveShell.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveDownloadedFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveDownloadedFileResponse")]
        System.Threading.Tasks.Task<PassiveShell.PassiveDownloadedFileResponse> PassiveDownloadedFileAsync(PassiveShell.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveGetDownloadFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveGetDownloadFileResponse")]
        PassiveShell.DownloadRequest PassiveGetDownloadFile(PassiveShell.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveGetDownloadFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveGetDownloadFileResponse")]
        System.Threading.Tasks.Task<PassiveShell.DownloadRequest> PassiveGetDownloadFileAsync(PassiveShell.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadRequest) of message DownloadRequest does not match the default value (PassiveGetUploadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveGetUploadFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveGetUploadFileResponse")]
        PassiveShell.RemoteFileInfo PassiveGetUploadFile(PassiveShell.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveGetUploadFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveGetUploadFileResponse")]
        System.Threading.Tasks.Task<PassiveShell.RemoteFileInfo> PassiveGetUploadFileAsync(PassiveShell.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveUploadedFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveUploadedFileResponse")]
        void PassiveUploadedFile(string id, string taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/PassiveUploadedFile", ReplyAction="http://tempuri.org/IPassiveShell/PassiveUploadedFileResponse")]
        System.Threading.Tasks.Task PassiveUploadedFileAsync(string id, string taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/ErrorUploadDownload", ReplyAction="http://tempuri.org/IPassiveShell/ErrorUploadDownloadResponse")]
        void ErrorUploadDownload(string id, string taskId, string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/ErrorUploadDownload", ReplyAction="http://tempuri.org/IPassiveShell/ErrorUploadDownloadResponse")]
        System.Threading.Tasks.Task ErrorUploadDownloadAsync(string id, string taskId, string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/Subscribe", ReplyAction="http://tempuri.org/IPassiveShell/SubscribeResponse")]
        bool Subscribe(string id, string version, string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/Subscribe", ReplyAction="http://tempuri.org/IPassiveShell/SubscribeResponse")]
        System.Threading.Tasks.Task<bool> SubscribeAsync(string id, string version, string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/ErrorNextCommand", ReplyAction="http://tempuri.org/IPassiveShell/ErrorNextCommandResponse")]
        void ErrorNextCommand(string id, string taskId, string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassiveShell/ErrorNextCommand", ReplyAction="http://tempuri.org/IPassiveShell/ErrorNextCommandResponse")]
        System.Threading.Tasks.Task ErrorNextCommandAsync(string id, string taskId, string response);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool FileEnded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool FreshStart;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string PathToSaveOnServer;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string taskId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(bool FileEnded, string FileName, string FileSize, bool FreshStart, long Length, string PathToSaveOnServer, string id, string taskId, byte[] FileByteStream) {
            this.FileEnded = FileEnded;
            this.FileName = FileName;
            this.FileSize = FileSize;
            this.FreshStart = FreshStart;
            this.Length = Length;
            this.PathToSaveOnServer = PathToSaveOnServer;
            this.id = id;
            this.taskId = taskId;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PassiveDownloadedFileResponse {
        
        public PassiveDownloadedFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool NewStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string PathInServer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string PathToSaveInClient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string taskId;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string FileName, bool NewStart, string PathInServer, string PathToSaveInClient, string id, string taskId) {
            this.FileName = FileName;
            this.NewStart = NewStart;
            this.PathInServer = PathInServer;
            this.PathToSaveInClient = PathToSaveInClient;
            this.id = id;
            this.taskId = taskId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPassiveShellChannel : PassiveShell.IPassiveShell, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassiveShellClient : System.ServiceModel.ClientBase<PassiveShell.IPassiveShell>, PassiveShell.IPassiveShell {
        
        public PassiveShellClient() {
        }
        
        public PassiveShellClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassiveShellClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassiveShellClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassiveShellClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsTransferingData() {
            return base.Channel.IsTransferingData();
        }
        
        public System.Threading.Tasks.Task<bool> IsTransferingDataAsync() {
            return base.Channel.IsTransferingDataAsync();
        }
        
        public void StartTransferData() {
            base.Channel.StartTransferData();
        }
        
        public System.Threading.Tasks.Task StartTransferDataAsync() {
            return base.Channel.StartTransferDataAsync();
        }
        
        public bool PassiveClientRun(string id, string taskId, string baseLine) {
            return base.Channel.PassiveClientRun(id, taskId, baseLine);
        }
        
        public System.Threading.Tasks.Task<bool> PassiveClientRunAsync(string id, string taskId, string baseLine) {
            return base.Channel.PassiveClientRunAsync(id, taskId, baseLine);
        }
        
        public System.Tuple<string, string, string> PassiveNextCommand(string id) {
            return base.Channel.PassiveNextCommand(id);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<string, string, string>> PassiveNextCommandAsync(string id) {
            return base.Channel.PassiveNextCommandAsync(id);
        }
        
        public void CommandResponse(string id, string taskId, string baseLine) {
            base.Channel.CommandResponse(id, taskId, baseLine);
        }
        
        public System.Threading.Tasks.Task CommandResponseAsync(string id, string taskId, string baseLine) {
            return base.Channel.CommandResponseAsync(id, taskId, baseLine);
        }
        
        public bool HasCommand(string id) {
            return base.Channel.HasCommand(id);
        }
        
        public System.Threading.Tasks.Task<bool> HasCommandAsync(string id) {
            return base.Channel.HasCommandAsync(id);
        }
        
        public bool HasUploadCommand(string id) {
            return base.Channel.HasUploadCommand(id);
        }
        
        public System.Threading.Tasks.Task<bool> HasUploadCommandAsync(string id) {
            return base.Channel.HasUploadCommandAsync(id);
        }
        
        public bool HasDownloadCommand(string id) {
            return base.Channel.HasDownloadCommand(id);
        }
        
        public System.Threading.Tasks.Task<bool> HasDownloadCommandAsync(string id) {
            return base.Channel.HasDownloadCommandAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PassiveShell.PassiveDownloadedFileResponse PassiveShell.IPassiveShell.PassiveDownloadedFile(PassiveShell.RemoteFileInfo request) {
            return base.Channel.PassiveDownloadedFile(request);
        }
        
        public void PassiveDownloadedFile(bool FileEnded, string FileName, string FileSize, bool FreshStart, long Length, string PathToSaveOnServer, string id, string taskId, byte[] FileByteStream) {
            PassiveShell.RemoteFileInfo inValue = new PassiveShell.RemoteFileInfo();
            inValue.FileEnded = FileEnded;
            inValue.FileName = FileName;
            inValue.FileSize = FileSize;
            inValue.FreshStart = FreshStart;
            inValue.Length = Length;
            inValue.PathToSaveOnServer = PathToSaveOnServer;
            inValue.id = id;
            inValue.taskId = taskId;
            inValue.FileByteStream = FileByteStream;
            PassiveShell.PassiveDownloadedFileResponse retVal = ((PassiveShell.IPassiveShell)(this)).PassiveDownloadedFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PassiveShell.PassiveDownloadedFileResponse> PassiveShell.IPassiveShell.PassiveDownloadedFileAsync(PassiveShell.RemoteFileInfo request) {
            return base.Channel.PassiveDownloadedFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<PassiveShell.PassiveDownloadedFileResponse> PassiveDownloadedFileAsync(bool FileEnded, string FileName, string FileSize, bool FreshStart, long Length, string PathToSaveOnServer, string id, string taskId, byte[] FileByteStream) {
            PassiveShell.RemoteFileInfo inValue = new PassiveShell.RemoteFileInfo();
            inValue.FileEnded = FileEnded;
            inValue.FileName = FileName;
            inValue.FileSize = FileSize;
            inValue.FreshStart = FreshStart;
            inValue.Length = Length;
            inValue.PathToSaveOnServer = PathToSaveOnServer;
            inValue.id = id;
            inValue.taskId = taskId;
            inValue.FileByteStream = FileByteStream;
            return ((PassiveShell.IPassiveShell)(this)).PassiveDownloadedFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PassiveShell.DownloadRequest PassiveShell.IPassiveShell.PassiveGetDownloadFile(PassiveShell.DownloadRequest request) {
            return base.Channel.PassiveGetDownloadFile(request);
        }
        
        public void PassiveGetDownloadFile(ref string FileName, ref bool NewStart, ref string PathInServer, ref string PathToSaveInClient, ref string id, ref string taskId) {
            PassiveShell.DownloadRequest inValue = new PassiveShell.DownloadRequest();
            inValue.FileName = FileName;
            inValue.NewStart = NewStart;
            inValue.PathInServer = PathInServer;
            inValue.PathToSaveInClient = PathToSaveInClient;
            inValue.id = id;
            inValue.taskId = taskId;
            PassiveShell.DownloadRequest retVal = ((PassiveShell.IPassiveShell)(this)).PassiveGetDownloadFile(inValue);
            FileName = retVal.FileName;
            NewStart = retVal.NewStart;
            PathInServer = retVal.PathInServer;
            PathToSaveInClient = retVal.PathToSaveInClient;
            id = retVal.id;
            taskId = retVal.taskId;
        }
        
        public System.Threading.Tasks.Task<PassiveShell.DownloadRequest> PassiveGetDownloadFileAsync(PassiveShell.DownloadRequest request) {
            return base.Channel.PassiveGetDownloadFileAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PassiveShell.RemoteFileInfo PassiveShell.IPassiveShell.PassiveGetUploadFile(PassiveShell.DownloadRequest request) {
            return base.Channel.PassiveGetUploadFile(request);
        }
        
        public bool PassiveGetUploadFile(ref string FileName, bool NewStart, string PathInServer, string PathToSaveInClient, ref string id, ref string taskId, out string FileSize, out bool FreshStart, out long Length, out string PathToSaveOnServer, out byte[] FileByteStream) {
            PassiveShell.DownloadRequest inValue = new PassiveShell.DownloadRequest();
            inValue.FileName = FileName;
            inValue.NewStart = NewStart;
            inValue.PathInServer = PathInServer;
            inValue.PathToSaveInClient = PathToSaveInClient;
            inValue.id = id;
            inValue.taskId = taskId;
            PassiveShell.RemoteFileInfo retVal = ((PassiveShell.IPassiveShell)(this)).PassiveGetUploadFile(inValue);
            FileName = retVal.FileName;
            FileSize = retVal.FileSize;
            FreshStart = retVal.FreshStart;
            Length = retVal.Length;
            PathToSaveOnServer = retVal.PathToSaveOnServer;
            id = retVal.id;
            taskId = retVal.taskId;
            FileByteStream = retVal.FileByteStream;
            return retVal.FileEnded;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PassiveShell.RemoteFileInfo> PassiveShell.IPassiveShell.PassiveGetUploadFileAsync(PassiveShell.DownloadRequest request) {
            return base.Channel.PassiveGetUploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<PassiveShell.RemoteFileInfo> PassiveGetUploadFileAsync(string FileName, bool NewStart, string PathInServer, string PathToSaveInClient, string id, string taskId) {
            PassiveShell.DownloadRequest inValue = new PassiveShell.DownloadRequest();
            inValue.FileName = FileName;
            inValue.NewStart = NewStart;
            inValue.PathInServer = PathInServer;
            inValue.PathToSaveInClient = PathToSaveInClient;
            inValue.id = id;
            inValue.taskId = taskId;
            return ((PassiveShell.IPassiveShell)(this)).PassiveGetUploadFileAsync(inValue);
        }
        
        public void PassiveUploadedFile(string id, string taskId) {
            base.Channel.PassiveUploadedFile(id, taskId);
        }
        
        public System.Threading.Tasks.Task PassiveUploadedFileAsync(string id, string taskId) {
            return base.Channel.PassiveUploadedFileAsync(id, taskId);
        }
        
        public void ErrorUploadDownload(string id, string taskId, string response) {
            base.Channel.ErrorUploadDownload(id, taskId, response);
        }
        
        public System.Threading.Tasks.Task ErrorUploadDownloadAsync(string id, string taskId, string response) {
            return base.Channel.ErrorUploadDownloadAsync(id, taskId, response);
        }
        
        public bool Subscribe(string id, string version, string nickName) {
            return base.Channel.Subscribe(id, version, nickName);
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeAsync(string id, string version, string nickName) {
            return base.Channel.SubscribeAsync(id, version, nickName);
        }
        
        public void ErrorNextCommand(string id, string taskId, string response) {
            base.Channel.ErrorNextCommand(id, taskId, response);
        }
        
        public System.Threading.Tasks.Task ErrorNextCommandAsync(string id, string taskId, string response) {
            return base.Channel.ErrorNextCommandAsync(id, taskId, response);
        }
    }
}
